# Generated by Django 2.0.4 on 2018-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subTitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
