# Generated by Django 2.0.4 on 2018-04-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pubData',
            new_name='pubDate',
        ),
    ]
